all: Lab5-Step3.c Lab5-Step4.c Lab5-Step5.c buyingMilkSol1.c buyingMilkSol2.c buyingMilkSol3.c buyingMilkSol4.c threadSynSem.c
	gcc -o 3 Lab5-Step3.c
	gcc -o 4 Lab5-Step4.c
	gcc -o 5 Lab5-Step5.c
	gcc -o milk1 buyingMilkSol1.c
	gcc -o milk2 buyingMilkSol2.c
	gcc -o milk3 buyingMilkSol3.c
	gcc -o milk4 buyingMilkSol4.c
	gcc -o thread threadSynSem.c

clean:; rm -f 3 4 5 milk1 milk2 milk3 milk4 thread