all: Lab2-Step1.c Lab2-Step3.c Lab2-Step5.c Lab2-Step6.c Lab2-Step7.c Lab2-Step8.c
	gcc -o 1 Lab2-Step1.c
	gcc -o 3 Lab2-Step3.c
	gcc -o 5 Lab2-Step5.c
	gcc -o 6 Lab2-Step6.c
	gcc -o 7 Lab2-Step7.c
	gcc -o 8 Lab2-Step8.c

clean:; rm -f 1 3 5 6 7 8