all: Lab3-Step1.c Lab3-Step2.c Lab3-Step3.c Lab3-Step4.c Lab3-Step5.c Lab3-Step6.c Lab3-Step7.c Lab3-Step8.c
	gcc -o 1 Lab3-Step1.c
	gcc -o 2 Lab3-Step2.c
	gcc -o 3 Lab3-Step3.c
	gcc -o 4 Lab3-Step4.c
	gcc -o 5 Lab3-Step5.c
	gcc -o 6 Lab3-Step6.c
	gcc -o 7 Lab3-Step7.c
	gcc -o 8 Lab3-Step8.c	

clean:; rm -f 1 2 3 4 5 6 7 8